fco_database/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from members import views as members_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('allauth.urls')),
    path('', members_views.index, name='member_index'),
    path('membership/', members_views.ViewMembership.as_view(), name='view_membership'),
    path('membership/<int:member_id>', members_views.ViewMembership.as_view(), name='view_membership_admin'),
    path('member/<int:member_id>', members_views.ViewMember.as_view(), name='view_member'),
    path('member/new', members_views.NewMember.as_view(), name='new_member'),
    path('membership/new/', members_views.NewMembership.as_view(), name='new_membership'),
    path('api/postcode/<str:post_code>/', members_views.postcode, name='postcode')
]

members/models.py
from django.db import models
from django.contrib.auth.models import User
from fco_database.lib import RandomFileName
from django.contrib.postgres.fields import ArrayField
from datetime import date
from .volunteer import calc_new_volunteer_expiry


class MembershipType(models.Model):
    name = models.CharField(max_length=32)
    code = models.CharField(max_length=1)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    concession_price = models.DecimalField(max_digits=5, decimal_places=2)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def url_name(self):
        return self.name.lower()


class Membership(models.Model):
    CONCESSION_CODES = {
        "STUDENT": "s",
        "PENSION": "p",
        "HEALTHCARE": "h",
        "OTHER": "o"
    }
    concession_choices = [
        (CONCESSION_CODES["STUDENT"], "Student"),
        (CONCESSION_CODES["PENSION"], "Pension"),
        (CONCESSION_CODES["HEALTHCARE"], "Healthcare"),
        (CONCESSION_CODES["OTHER"], "Other")
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    membership_type = models.ForeignKey(MembershipType, on_delete=models.SET("OLD_MEMBERSHIP"))
    membership_expiry = models.DateField(null=True, blank=True)
    working_expiry = models.DateField(null=True, blank=True)
    concession = models.BooleanField(default=False)
    concession_proof = models.ImageField(upload_to=RandomFileName('concession_images'), blank=True, null=True)
    concession_type = models.CharField(max_length=1, choices=concession_choices, null=True, blank=True)
    paid = models.BooleanField(default=False)
    membership_active = models.BooleanField(default=False)
    ts_entered = models.DateTimeField(auto_now_add=True)
    ts_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

    @property
    def has_working_discount(self):
        if self.working_expiry is None:
            return False
        else:
            return self.working_expiry >= date.today()

    @staticmethod
    def get_membership_from_user(user):
        return Membership.objects.get(user=user)

    @property
    def can_add_member(self):
        members_count = Member.objects.filter(membership=self).count()
        print(self.membership_type.__str__())
        if self.membership_type.__str__() == "Individual":
            return members_count < 1
        elif self.membership_type.__str__() == "Couple":
            return members_count < 2
        elif self.membership_type.__str__() == "Household":
            return members_count < 5
        else:
            return False


class Member(models.Model):
    membership = models.ForeignKey(Membership, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=35)
    last_name = models.CharField(max_length=35)
    email = models.EmailField()
    phone_number = models.CharField(max_length=16, null=True, blank=True)
    postcode = models.CharField(max_length=4, null=True, blank=True)
    suburb = models.CharField(max_length=32, null=True, blank=True)
    mailing_list = models.BooleanField(default=True)
    volunteer_preferences = ArrayField(models.CharField(max_length=32), null=True, blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.email

    @staticmethod
    def get_form_fields():
        #return [getattr(field, field.name) for field in Member._meta.get_fields()].remove("membership")
        return ["first_name", "last_name", "email", "phone_number",
                "postcode", "suburb", "mailing_list", "volunteer_preferences"]


class Shift(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    date = models.DateField()
    hours = models.DecimalField(decimal_places=1, max_digits=3)
    #entered_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    ts_entered = models.DateTimeField(auto_now_add=True)
    ts_updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super(Shift, self).save(*args, **kwargs)
        membership = self.member.membership
        member_number = Member.objects.filter(membership=membership).count()
        membership.working_expiry = calc_new_volunteer_expiry(self.hours, membership.working_expiry, member_number)
        membership.save()


class VolunteerOption(models.Model):
    name = models.CharField(max_length=32)
    info = models.TextField(blank=True, null=True)

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import response
from django.views import generic
from . import models
from .forms import MembershipForm, MemberForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import IntegrityError
import requests
from querystring_parser import parser
from django.core.exceptions import PermissionDenied


@login_required
def index(request):
    try:
        membership = models.Membership.objects.get(user=request.user)
    except models.Membership.DoesNotExist:
        membership = None

    if membership is None:
        return redirect('new_membership')

    members = models.Member.objects.filter(membership=membership)
    context = {
        'membership': membership,
        'members': members
    }
    return render(request, "member/member_index.html", context)


class NewMembership(LoginRequiredMixin, generic.View):
    def get(self, request, form=None):
        try:
            potential_membership = models.Membership.objects.get(user=request.user)
        except models.Membership.DoesNotExist:
            potential_membership = None

        if potential_membership is not None:  # a membership exists
            if models.Member.objects.filter(
                    membership=potential_membership):  # a membership exists with no member details
                messages.info(request, "You already have a membership!")
                return redirect("member_index")
            else:
                messages.info(request, "Please finish your membership application before continuing")

        return self.show_form(request, form)

    def show_form(self, request, form):
        context = {
            'membership_types': models.MembershipType.objects.filter(active=True),
            'volunteer_options': models.VolunteerOption.objects.all(),
            'form': form
        }
        return render(request, "member/new_membership.html", context)

    def post(self, request):
        form = MembershipForm(parser.parse(request.POST.urlencode()))

        if not form.valid:
            messages.error(request, "There was an error in the form. Please try again")
            return self.get(request, form.data)

        new_membership = models.Membership()
        new_membership.user = request.user
        new_membership.membership_type = models.MembershipType.objects.get(code=form.membership_type)
        new_membership.concession = form.concession
        new_membership.concession_type = form.concession_type

        try:
            new_membership.save()
        except IntegrityError:
            messages.error(request, "There was an error in the form. Please try again")
            return self.get(request, form.data)
        except RuntimeError:
            messages.error(request, "There was server error. Please try again later")
            return self.get(request, form.data)

        new_members = []
        for member in form.members:
            new_member = models.Member.objects.create(**member, membership=new_membership)
            new_members.append(new_member)

        for member_model in new_members:
            try:
                member_model.save()
            except IntegrityError:
                messages.error(request, "There was an error in the form. Please try again")
                print(new_membership)
                new_membership.delete()
                return self.get(request, form.data)
            except RuntimeError:
                messages.error(request, "There was server error. Please try again later")
                print(new_membership)
                new_membership.delete()
                return self.get(request, form.data)

        return redirect("member_index")


@login_required
def postcode(request, post_code):
    data = requests.get("http://v0.postcodeapi.com.au/suburbs/{}.json".format(post_code))
    return response.HttpResponse(data.content, content_type='application/json')


class ViewMembership(LoginRequiredMixin, generic.View):
    def get(self, request, member_id=None, form=None):
        if member_id is None:
            try:
                membership = models.Membership.objects.get(user=request.user)
            except models.Membership.DoesNotExist:
                return NewMembership.show_form(request)
        else:
            try:
                membership = models.Membership.objects.get(pk=member_id)
            except models.Membership.DoesNotExist:
                raise response.Http404

        members = models.Member.objects.filter(membership=membership)
        # TODO: add payments model here
        context = {
            'membership': membership,
            'members': members,
            'volunteer_options': models.VolunteerOption.objects.all(),
            'form': form,
            # TODO: add boolean if more members are able to be put on membership
        }
        return render(request, "member/view_membership.html", context)

    def post(self, request):
        pass


class ViewMember(LoginRequiredMixin, generic.View):
    def get(self, request, member_id, form=None):
        try:
            member = models.Member.objects.get(pk=member_id)
        except models.Member.DoesNotExist:
            raise response.Http404

        try:
            membership = models.Membership.objects.get(user=request.user)
        except models.Membership.DoesNotExist:
            raise response.Http404

        if member.membership != membership:
            raise PermissionDenied
        else:
            context = {
                'volunteer_options': models.VolunteerOption.objects.all(),
                'member': member,
                'form': form
            }
            return render(request, "member/view_member.html", context)

    def post(self, request, member_id):
        form = MemberForm(parser.parse(request.POST.urlencode()))

        if not form.valid:
            print(form.errors)
            messages.error(request, "There was an error in the form. Please try again")
            return self.get(request, member_id, form)

        membership = models.Membership.objects.get(user=request.user)
        member = models.Member.objects.get(pk=member_id)

        if member.membership.pk is not membership.pk:
            raise PermissionDenied

        for key, value in form.data.items():
            setattr(member, key, value)

        try:
            member.save()
        except RuntimeError:
            messages.error(request, "There was an error in the form. Please try again later")
            return self.get(request, member_id, form)
        except IntegrityError:
            messages.error(request, "There was an error in the form. Please try again later")
            return self.get(request, member_id, form)

        return redirect("view_membership")


class NewMember(LoginRequiredMixin, generic.View):
    def get(self, request, form=None):
        membership = models.Membership.get_membership_from_user(request.user)
        if not membership.can_add_member:
            messages.info(request, "You have the maximum number of members on your membership")
            return redirect("view_membership")

        context = {
            'volunteer_options': models.VolunteerOption.objects.all(),
            'form': form
        }
        return render(request, "member/new_member.html", context)

    def post(self, request, form=None):
        form = MemberForm(parser.parse(request.POST.urlencode()))

        if not form.valid:
            messages.error(request, "There was an error in the form. Please try again")
            return self.get(request, form)

        membership = models.Membership.get_membership_from_user(request.user)
        if not membership.can_add_member:
            messages.info(request, "You have the maximum number of members on your membership")
            return redirect("view_membership")

        new_member = models.Member.objects.create(**form.data, membership=membership)
        try:
            new_member.save()
        except RuntimeError:
            messages.error(request, "There was an error in the form. Please try again later")
            return self.get(request, form)
        except IntegrityError:
            messages.error(request, "There was an error in the form. Please try again later")
            return self.get(request, form)

        return redirect("view_membership")

templates/member/member_index.html
{% extends 'account/base.html' %}

{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-3">
            <div class="card mb-2">
                <div class="card-header">
                    My Membership
                    {% if membership.membership_active %}
                                <span class="badge badge-success">Active</span>
                            {% else %}
                                <span class="badge badge-danger">Inactive</span>
                            {% endif %}
                </div>
                <div class="card-body">
                    {% if membership.paid %}
                        <p>
                            <strong>Expiry: </strong>
                            {{ membership.membership_expiry|date:"d F Y" }}

                        </p>
                        <p>
                            <strong>Working Discount: </strong>
                            {% if membership.has_working_discount %}
                                <span class="badge badge-success">Active</span>
                                <br/>
                                <em>You will recieve 20% off supermarket items until {{ membership.working_expiry|date:"d F Y" }}</em>
                            {% else %}
                                <span class="badge badge-danger">Inactive</span>
                                <br/>
                                <em>You will receive 5% off supermarket items</em>
                            {% endif %}
                        </p>
                        {% comment %}{% if membership.concession %}
                            <p>
                                <strong>Concession: </strong>
                                <span class="badge badge-success">Yes ({{ membership.get_concession_type_display }})</span>
                            </p>
                        {% endif %}{% endcomment %}
                        {% comment %}<p><strong>Created: </strong> {{ membership.ts_entered|date:"d F Y" }}</p>{% endcomment %}
                    {% else %}
                        <strong>Your membership is not active without <a href="#">payment</a> of membership fees.</strong>
                    {% endif %}
                    <a class="btn btn-primary" href="{% url "view_membership" %}">View/Edit Membership</a>
                </div>
            </div>
            <div class="list-group">
                {% for member in members %}
                    <a href="{% url "view_member" member_id=member.pk %}" class="list-group-item list-group-item-action">
                        {{ member.first_name }} {{ member.last_name }} <br/>
                        <small>{{ member.email }}</small>
                    </a>
                {% endfor %}
            </div>
        </div>

        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="text-center">Canberra Food Co-op Members</h3>
                    <div class="row">
                        <div class="col">
                            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
                                egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
                                Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris
                                placerat eleifend leo.</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="list-group">
                <a class="list-group-item list-group-item-light">Quick Actions</a>
                <a href="#" class="list-group-item list-group-item-action">Renew Membership</a>
                <a href="#" class="list-group-item list-group-item-action">View Working Hours</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/member/view_membership.html
{% extends 'account/base.html' %}

{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card mb-4">
                <div class="card-header">
                    Membership Details
                </div>
                <div class="card-body">
                    <p>
                        <strong>Type:</strong>
                        {{ membership.membership_type }}
                        <a href="#">(update)</a>
                    </p>
                    <p>
                        <strong>Expiry: </strong>
                        {{ membership.membership_expiry|date:"d F Y" }}
                        <a href="#">(renew)</a>

                    </p>
                    <p>
                        <strong>Working Discount: </strong>
                        {% if membership.has_working_discount %}
                            <span class="badge badge-success">Active</span>
                            <br/>
                            <em>You will receive 20% off supermarket items
                                until {{ membership.working_expiry|date:"d F Y" }}</em>
                        {% else %}
                            <span class="badge badge-danger">Inactive</span>
                            <br/>
                            <em>You will receive 5% off supermarket items</em>
                        {% endif %}
                    </p>
                    {% if membership.concession %}
                        <p>
                            <strong>Concession: </strong>
                            <span class="badge badge-success">Yes ({{ membership.get_concession_type_display }})</span>
                        </p>
                    {% endif %}
                    <p><strong>Created: </strong> {{ membership.ts_entered|date:"d F Y" }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    Payment History
                </div>
                <div class="card-body">
                    Payment information here
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                    Members
                </div>
                <div class="card-body">
                <p>Click on the member to edit or delete them.</p>
                    <table class="table hover">
                        <thead class="thead-light">
                            <tr>
                              <th scope="col">Name</th>
                              <th scope="col">Email</th>
                              <th scope="col">Phone Number</th>
                              <th scope="col">Volunteering</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for member in members %}
                                <tr>
                                    <td>
                                        <a href="{% url "view_member" member_id=member.pk %}">
                                            {{ member.first_name }} {{ member.last_name }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ member.email }}
                                    </td>
                                    <td>
                                        {{ member.phone_number }}
                                    </td>
                                    <td>
                                        {{ member.volunteer_preferences|join:", " }}
                                    </td>
                                </tr>
                            {% endfor %}
                        {% if membership.can_add_member %}
                            <tr>
                                <td colspan="4">
                                    <a href="{% url "new_member" %}" class="btn btn-primary btn-sm">
                                        Add a member
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}